version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    assignees:
      - franky47
    labels:
      - dependencies
      - javascript
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    assignees:
      - franky47
    labels:
      - dependencies
      - github_actions
