version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Europe/Paris
    assignees:
      - franky47
    labels:
      - dependencies
      - javascript
      - valet:merge
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    assignees:
      - franky47
    labels:
      - dependencies
      - github_actions
      - valet:merge
