language: node_js

node_js:
  - node

cache: yarn

script:
  - yarn ci

deploy:
  provider: npm
  email: accounts@francoisbest.com
  api_key:
    secure: boQyx0Q9EIHJyo0qX4V9B8haiwZWV0KRgTubpcNOTG3qXI/AMmyXe7/uuMQ058tEquDR0XTcGwhWT4IGtdA7FpA08kN/gQDxICKBcI+GQD/pR9MB3w+XRgU3mzm/va3iPTSiddJTId5QLeRvflXcFv6qnON+1diaZnFAemAHVTwH7N+PO1bpKZ2hYdWG7obU673shL0AfCzT1YrILcVVopmWIgVLOCU6e2JQEXth4ho/AqiIRqNMpd+vgEDBSWWUBUt7j1tzJWQl7cVeTlqsLjmu2DCKWAFXy76KbfIdVTA2vLQrTgd7fcT7hM+R5ne+LQACxNODhTWf/w0Js6DHXocWjFualnpPm4LuCA31y47ZsXzYDG2PEQ3Ri4r7yU0VAOjODWjxlW0ggl0keK1FoznhG/8ikm5QWAAHW0EKsP/F+d9jtJrgQ/ml3+WGyNyTUE9LWepGASbfaAyASik5AqSu7JU2dCs3OHgsRqmsT0/fBRIRdxJgyPvMs+kUwQHyiPcQVkPIM4mZU1kqYIsGXbA0Im3fb/rmh4dHR1019rbYi2fbY93icaD5PJ4X2uSDH3yERo26rvsYU2EQis9bbWHyteL5CXeI9Z3ao4dwbMUtvaaNcQJ+Z4MXwuppPAF9etSabg4C6RJxMRP6q1lOiF0FVgFLqVpGMtKgHEUW4Gk=
  on:
    tags: true
  skip_cleanup: true

notifications:
  slack:
    rooms:
      secure: NlYYsdOuF9piH2D6Co91HtZ8hm34kLXybLCFrAUPgp2LLuS4PDujyltOWynOmhmEb81tEEwHpHtky78cfL3iOqR5nlx2GwSPTo1uiCA96OMhp6m3Jy8EfSy1R4DSF35FI6xjaXPSZUEgAeoJyOVHmWjUgD3oIt4PZYgRRca3ijDph946AS5LnGIYtDFgt0wZ1iAte4XLoXsG0ofvMGM8EiLbJ3LBpL72Qnp1XERkgv9wRHay3wPxuBZ8WlMoSwOgKhM1LLjVbOwEtWXNyEy5dAJvvgYdImxUrtIkE3IH61mVWz2aEG2gaJ9tkjQRv+Ct+ZCNgOgltc3AJ0TmVjW85cf9ba/IsSsufhcfLgUrirCoVXz6LXQcUcs0sgasESpVqnub/XP2B/GgE/Kbb8anZ6wbQsog5dY9PeDEwXJ5TemVY6C5TwW+Hs4mmT+e/m4ECSsEY/Ve1gtu2i2DlhqOgRYgN3B3jCZJX3NGXKTIk4jFajCLE9dyEueUVvntmQNG81nQKmOCFesI0xiCF95B3Nm+Ba6loY04gJnXQXKMsyQJYhGatJ7oBEsr2djHPJXcuXvFvwWb2fEKXoMcJWD6NOCaxm8nDXq5KQZ5tgpWZgOfl21H/S3Mv+i92qsZDmfAL9mGNCftpEClE+HBENjlFkO6nEKJtjt2N9Cip8MwzAo=
    on_success: always
    on_failure: always
    on_error: always
    template:
      - 'Build %{result}: %{repository_slug}'
      - 'Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) on %{branch} by %{author} %{result} in %{duration}'
