language: node_js

node_js:
  - node

cache: yarn

script:
  - yarn ci

deploy:
  provider: npm
  email: accounts@francoisbest.com
  api_key:
    secure: boQyx0Q9EIHJyo0qX4V9B8haiwZWV0KRgTubpcNOTG3qXI/AMmyXe7/uuMQ058tEquDR0XTcGwhWT4IGtdA7FpA08kN/gQDxICKBcI+GQD/pR9MB3w+XRgU3mzm/va3iPTSiddJTId5QLeRvflXcFv6qnON+1diaZnFAemAHVTwH7N+PO1bpKZ2hYdWG7obU673shL0AfCzT1YrILcVVopmWIgVLOCU6e2JQEXth4ho/AqiIRqNMpd+vgEDBSWWUBUt7j1tzJWQl7cVeTlqsLjmu2DCKWAFXy76KbfIdVTA2vLQrTgd7fcT7hM+R5ne+LQACxNODhTWf/w0Js6DHXocWjFualnpPm4LuCA31y47ZsXzYDG2PEQ3Ri4r7yU0VAOjODWjxlW0ggl0keK1FoznhG/8ikm5QWAAHW0EKsP/F+d9jtJrgQ/ml3+WGyNyTUE9LWepGASbfaAyASik5AqSu7JU2dCs3OHgsRqmsT0/fBRIRdxJgyPvMs+kUwQHyiPcQVkPIM4mZU1kqYIsGXbA0Im3fb/rmh4dHR1019rbYi2fbY93icaD5PJ4X2uSDH3yERo26rvsYU2EQis9bbWHyteL5CXeI9Z3ao4dwbMUtvaaNcQJ+Z4MXwuppPAF9etSabg4C6RJxMRP6q1lOiF0FVgFLqVpGMtKgHEUW4Gk=
  on:
    tags: true
  skip_cleanup: true

notifications:
  slack:
    secure: Bkc0t5LlN49ow6DdUV4fiCDHbgT3LpPuXCMGklRqe+gJKVDT7hFdqYh6HIpgXinANbZYqLQDHvktLBmvr3FQ2DFQn9aEs6StiL81xSMqSQA3QuOP3EP3ruRp7bEbaVMZ6fmaacswMt5dXrfdglhNICmMUU2eJLyaNZee5+2vv6MY0DMnRoVZpgTlpo/LO4W0L90f4KAEocR+XB/Y/Fc6BCb0N5U4ZavmSZOZYMtV1BshmFw164gnF1QM6NZgqEPxTzHpBjerDD3585kbCK6qp4Wi148JttXrC6TRS202W180lGT7gasSHkaSc5oQ7FST2+oXa0ngP0T3pz3O6VwxygWmtMrDHWeCHNQsieQZnVkh3L/2SuEyJcYtkR53XXeX2eWydomp/kY65UQsi7TYxdLCqQieVGjiz2TyUAlkPGwZv4IsZpzWoB4kZk1GoF509HiXMCTmnK7qOnI1lVr+8WlDMruWgutMmCHiy6+6oap+Hyo8AKJCtb/faQCU9d5xKfF+C/ui8uskFVLYu3gNHxDXBQf7gQka/C1qz+fxN65Grthrxq0mjag4uwDJ+Jse0pAY2dpb46WDL24mZf8xtlHCVdplwiT1UzUivUpXHuye83B28oVIH/8OwVo25kCX3lVLiCdbtwvykqnhoXrWqX95DFf93foXCPaR0BETFd0=
    on_success: always
    on_failure: always
