language: node_js

node_js:
  - node

cache: yarn

script:
  - yarn ci

notifications:
  slack:
    secure: Bkc0t5LlN49ow6DdUV4fiCDHbgT3LpPuXCMGklRqe+gJKVDT7hFdqYh6HIpgXinANbZYqLQDHvktLBmvr3FQ2DFQn9aEs6StiL81xSMqSQA3QuOP3EP3ruRp7bEbaVMZ6fmaacswMt5dXrfdglhNICmMUU2eJLyaNZee5+2vv6MY0DMnRoVZpgTlpo/LO4W0L90f4KAEocR+XB/Y/Fc6BCb0N5U4ZavmSZOZYMtV1BshmFw164gnF1QM6NZgqEPxTzHpBjerDD3585kbCK6qp4Wi148JttXrC6TRS202W180lGT7gasSHkaSc5oQ7FST2+oXa0ngP0T3pz3O6VwxygWmtMrDHWeCHNQsieQZnVkh3L/2SuEyJcYtkR53XXeX2eWydomp/kY65UQsi7TYxdLCqQieVGjiz2TyUAlkPGwZv4IsZpzWoB4kZk1GoF509HiXMCTmnK7qOnI1lVr+8WlDMruWgutMmCHiy6+6oap+Hyo8AKJCtb/faQCU9d5xKfF+C/ui8uskFVLYu3gNHxDXBQf7gQka/C1qz+fxN65Grthrxq0mjag4uwDJ+Jse0pAY2dpb46WDL24mZf8xtlHCVdplwiT1UzUivUpXHuye83B28oVIH/8OwVo25kCX3lVLiCdbtwvykqnhoXrWqX95DFf93foXCPaR0BETFd0=
    on_success: always
    on_failure: always
